#!/usr/bin/env node

const fs = require('fs/promises')
const path = require('path')
const { polishKidReadableText } = require('./lib/kids-bible-style')

const BOOK = 'Numbers'
const BOOK_SLUG = 'numbers'
const SOURCE_BASE = 'https://www.canonapi.com/v1/numbers'
const EXPECTED_VERSE_COUNTS = [
  54, 34, 51, 49, 31, 27, 89, 26, 23, 36, 35, 16, 33, 45, 41, 50, 13, 32,
  22, 29, 35, 41, 30, 25, 18, 65, 23, 31, 40, 16, 54, 42, 56, 29, 34, 13,
]

async function main() {
  for (let chapter = 1; chapter <= EXPECTED_VERSE_COUNTS.length; chapter += 1) {
    const verses = await fetchChapter(chapter)
    const expectedCount = EXPECTED_VERSE_COUNTS[chapter - 1]
    if (verses.length !== expectedCount) {
      throw new Error(`Expected ${BOOK} ${chapter} to have ${expectedCount} verses, got ${verses.length}`)
    }

    await writeChapter(chapter, '5-7', verses.map(text => adaptText(text, '5-7')))
    await writeChapter(chapter, '8-10', verses.map(text => adaptText(text, '8-10')))
    console.log(`Wrote ${BOOK} ${chapter} (${verses.length} verses)`)
  }
}

async function fetchChapter(chapter) {
  const response = await fetch(`${SOURCE_BASE}/${chapter}.json`)
  if (!response.ok) {
    throw new Error(`Failed to fetch ${BOOK} ${chapter}: ${response.status} ${response.statusText}`)
  }

  const verses = await response.json()
  if (!Array.isArray(verses) || !verses.length) {
    throw new Error(`No verses returned for ${BOOK} ${chapter}`)
  }

  return verses
}

async function writeChapter(chapter, ageRange, verses) {
  const directory = path.join(
    process.cwd(),
    'content',
    'bible-text',
    `ages-${ageRange}`,
    'old-testament',
    BOOK_SLUG
  )
  await fs.mkdir(directory, { recursive: true })

  const body = [
    `# ${BOOK} ${chapter}`,
    '',
    '## Book',
    BOOK,
    '',
    '## Chapter',
    String(chapter),
    '',
    '## Verses',
    '',
    ...verses.flatMap((text, index) => [
      `### ${BOOK} ${chapter}:${index + 1}`,
      text,
      '',
    ]),
  ].join('\n')

  await fs.writeFile(path.join(directory, `chapter-${chapter}.md`), body, 'utf8')
}

function adaptText(source, ageRange) {
  let text = normalizeSource(source)

  text = text
    .replace(/\bYahweh\b/g, 'the Lord')
    .replace(/\bchildren of Israel\b/gi, 'people of Israel')
    .replace(/\bchild of Israel\b/gi, 'person of Israel')
    .replace(/\bchildren of ([A-Z][a-z]+)\b/g, 'descendants of $1')
    .replace(/\bChildren of ([A-Z][a-z]+)\b/g, 'Descendants of $1')
    .replace(/\bstranger\b/g, 'foreigner')
    .replace(/\bstrangers\b/g, 'foreigners')
    .replace(/\bsojourner\b/g, 'foreigner living among you')
    .replace(/\bsojourners\b/g, 'foreigners living among you')
    .replace(/\balien\b/g, 'foreigner')
    .replace(/\baliens\b/g, 'foreigners')
    .replace(/\bcongregation\b/g, 'community')
    .replace(/\bCongregation\b/g, 'Community')
    .replace(/\bassembly\b/g, 'gathered people')
    .replace(/\bAssembly\b/g, 'Gathered people')
    .replace(/\bordinances\b/g, 'commands')
    .replace(/\bordinance\b/g, 'command')
    .replace(/\bcommandments\b/g, 'commands')
    .replace(/\bcommandment\b/g, 'command')
    .replace(/\bstatutes\b/g, 'rules')
    .replace(/\bstatute\b/g, 'rule')
    .replace(/\biniquity\b/g, 'sin')
    .replace(/\biniquities\b/g, 'sins')
    .replace(/\bsanctified\b/g, 'made holy')
    .replace(/\bsanctifies\b/g, 'makes holy')
    .replace(/\bsanctify\b/g, 'make holy')
    .replace(/\btrespass offering\b/g, 'guilt offering')
    .replace(/\btrespass offerings\b/g, 'guilt offerings')
    .replace(/\bmeal offering\b/g, 'grain offering')
    .replace(/\bMeal offering\b/g, 'Grain offering')
    .replace(/\boffering by fire\b/g, 'offering burned on the altar')
    .replace(/\bofferings by fire\b/g, 'offerings burned on the altar')
    .replace(/\boffering made by fire\b/g, 'offering burned on the altar')
    .replace(/\bofferings made by fire\b/g, 'offerings burned on the altar')
    .replace(/\bpleasant aroma\b/g, 'pleasing smell')
    .replace(/\bholy convocation\b/g, 'holy gathering')
    .replace(/\bholy convocations\b/g, 'holy gatherings')
    .replace(/\bthroughout your generations\b/g, 'for all your generations')
    .replace(/\bthroughout their generations\b/g, 'for all their generations')
    .replace(/\bthroughout his generations\b/g, 'for all his generations')
    .replace(/\bthroughout her generations\b/g, 'for all her generations')
    .replace(/\bcarcass\b/g, 'dead body')
    .replace(/\bcarcasses\b/g, 'dead bodies')
    .replace(/\bcorpse\b/g, 'dead body')
    .replace(/\bcorpses\b/g, 'dead bodies')
    .replace(/\btabernacle of the Testimony\b/g, 'Tabernacle of the Testimony')
    .replace(/\bTabernacle of the Testimony\b/g, 'Tent of the Testimony')
    .replace(/\btabernacle\b/g, 'tent')
    .replace(/\bTabernacle\b/g, 'Tent')
    .replace(/\bTent of the Testimony\b/g, 'Tent of the Testimony')
    .replace(/\bfathers' houses\b/g, 'family houses')
    .replace(/\bfathers' households\b/g, 'family households')
    .replace(/\bfathers' house\b/g, 'family house')
    .replace(/\bfather's house\b/g, 'family house')
    .replace(/\bstandard\b/g, 'banner')
    .replace(/\bstandards\b/g, 'banners')
    .replace(/\bencamp\b/g, 'camp')
    .replace(/\bencamps\b/g, 'camps')
    .replace(/\bencamped\b/g, 'camped')
    .replace(/\bpitch their tents\b/g, 'set up their tents')
    .replace(/\bjourneyed\b/g, 'traveled')
    .replace(/\bjourney\b/g, 'travel')
    .replace(/\bjourneys\b/g, 'travels')
    .replace(/\bmurmured\b/g, 'complained')
    .replace(/\bmurmur\b/g, 'complain')
    .replace(/\bmurmurings\b/g, 'complaints')
    .replace(/\blusted exceedingly\b/g, 'craved very strongly')
    .replace(/\blusted\b/g, 'craved')
    .replace(/\bmultitude\b/g, 'crowd')
    .replace(/\bmixed multitude\b/g, 'mixed crowd')
    .replace(/\bprey\b/g, 'plunder')
    .replace(/\bbooty\b/g, 'plunder')
    .replace(/\bspoil\b/g, 'plunder')
    .replace(/\butterly destroy\b/g, 'completely destroy')
    .replace(/\bdivination\b/g, 'divination')
    .replace(/\bsoothsayer\b/g, 'person who practiced divination')
    .replace(/\bwhoredom\b/g, 'sexual sin')
    .replace(/\bprostitution\b/g, 'unfaithfulness')
    .replace(/\bprostitute\b/g, 'person living in sexual sin')
    .replace(/\bprostitutes\b/g, 'people living in sexual sin')
    .replace(/\bfornication\b/g, 'sexual sin')
    .replace(/\bdefile\b/g, 'make unclean')
    .replace(/\bdefiles\b/g, 'makes unclean')
    .replace(/\bdefiled\b/g, 'made unclean')
    .replace(/\bunclean by reason of the dead\b/g, 'unclean because of a dead body')
    .replace(/\bunclean by a dead body\b/g, 'unclean because of a dead body')
    .replace(/\bunclean by a corpse\b/g, 'unclean because of a dead body')
    .replace(/\bleprosy\b/g, 'serious disease')
    .replace(/\bleprous\b/g, 'serious')
    .replace(/\bleper\b/g, 'person with a serious disease')
    .replace(/\blepers\b/g, 'people with a serious disease')
    .replace(/\bplague\b/g, 'terrible sickness')
    .replace(/\bplagues\b/g, 'terrible sicknesses')
    .replace(/\bcut off from his people\b/g, 'removed from his people')
    .replace(/\bcut off from her people\b/g, 'removed from her people')
    .replace(/\bcut off from their people\b/g, 'removed from their people')
    .replace(/\bcut off from among his people\b/g, 'removed from among his people')
    .replace(/\bcut off from among her people\b/g, 'removed from among her people')
    .replace(/\bcut off from among their people\b/g, 'removed from among their people')
    .replace(/\bgathered to your people\b/g, 'gathered to your people in death')
    .replace(/\bgathered to his people\b/g, 'gathered to his people in death')
    .replace(/\bgathered to her people\b/g, 'gathered to her people in death')
    .replace(/\bkinsman\b/g, 'relative')
    .replace(/\bkinsmen\b/g, 'relatives')
    .replace(/\bunwittingly\b/g, 'without meaning to')
    .replace(/\bman slayer\b/g, 'person who killed someone')
    .replace(/\bmanslayer\b/g, 'person who killed someone')
    .replace(/\bavenger of blood\b/g, 'relative who avenges the death')
    .replace(/\bbowels\b/g, 'body')
    .replace(/\bbathe his flesh\b/g, 'bathe his body')
    .replace(/\bbathe her flesh\b/g, 'bathe her body')
    .replace(/\bbathe their flesh\b/g, 'bathe their body')
    .replace(/\bboth of man and of animal\b/g, 'both people and animals')
    .replace(/\bboth of man and animal\b/g, 'both people and animals')
    .replace(/\bboth man and animal\b/g, 'both people and animals')
    .replace(/\blest\b/g, 'or else')
    .replace(/\bsouls\b/g, 'people')
    .replace(/\bsoul\b/g, 'person')

  text = modernizeCommandLanguage(text)
  text = clarifySensitiveLanguage(text)

  if (ageRange === '5-7') {
    text = text
      .replace(/\blivestock\b/g, 'animals')
      .replace(/\bdivisions\b/g, 'groups')
      .replace(/\bdivision\b/g, 'group')
      .replace(/\btribe\b/g, 'tribe')
      .replace(/\bprince\b/g, 'leader')
      .replace(/\bprinces\b/g, 'leaders')
      .replace(/\bheads of\b/g, 'leaders of')
      .replace(/\bwithout blemish\b/g, 'with nothing wrong with it')
      .replace(/\bwithout defect\b/g, 'with nothing wrong with it')
      .replace(/\bgarments\b/g, 'clothes')
      .replace(/\bconsecrate\b/g, 'set apart')
      .replace(/\bconsecrated\b/g, 'set apart')
      .replace(/\bconsecration\b/g, 'setting apart')
      .replace(/\bmake atonement for him\b/g, 'make atonement for him, helping make things right with God')
      .replace(/\bmake atonement for her\b/g, 'make atonement for her, helping make things right with God')
      .replace(/\bmake atonement for them\b/g, 'make atonement for them, helping make things right with God')
      .replace(/\bmake atonement for you\b/g, 'make atonement for you, helping make things right with God')
      .replace(/\bmake atonement for the people of Israel\b/g, 'make atonement for the people of Israel, helping make things right with God')
      .replace(/\bmake atonement for the people\b/g, 'make atonement for the people, helping make things right with God')
      .replace(/\bcommunity\b/g, 'whole group')
      .replace(/\bgathered people\b/g, 'whole group')
      .replace(/\babomination\b/g, 'detestable thing')
      .replace(/\babominations\b/g, 'detestable things')
  } else {
    text = text
      .replace(/\bwithout blemish\b/g, 'without any blemish')
      .replace(/\bconsecrate\b/g, 'set apart')
      .replace(/\bconsecrated\b/g, 'set apart')
      .replace(/\bconsecration\b/g, 'setting apart')
      .replace(/\babomination\b/g, 'detestable thing')
      .replace(/\babominations\b/g, 'detestable things')
  }

  return polishKidReadableText(polishText(text), ageRange)
}

function normalizeSource(source) {
  return String(source)
    .replace(/\u00a0/g, ' ')
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/[—–]/g, '-')
    .replace(/\s+/g, ' ')
    .replace(/^"\s*'\s*/, '"')
    .replace(/^'\s*/, '')
    .replace(/\s*'\s*$/g, '')
    .trim()
}

function modernizeCommandLanguage(text) {
  return text
    .replace(/\bshall not\b/g, 'must not')
    .replace(/\bshall never\b/g, 'must never')
    .replace(/\bshall be put to death\b/g, 'must be put to death')
    .replace(/\bshall surely be put to death\b/g, 'must surely be put to death')
    .replace(/\bshall die\b/g, 'must die')
    .replace(/\bshall be forgiven\b/g, 'will be forgiven')
    .replace(/\bshall be accepted\b/g, 'will be accepted')
    .replace(/\bshall be clean\b/g, 'will be clean')
    .replace(/\bshall be unclean\b/g, 'will be unclean')
    .replace(/\bshall be holy\b/g, 'will be holy')
    .replace(/\bshall come\b/g, 'will come')
    .replace(/\bshall rise\b/g, 'will rise')
    .replace(/\bshall strike\b/g, 'will strike')
    .replace(/\bshall break down\b/g, 'will break down')
    .replace(/\bshall destroy\b/g, 'will destroy')
    .replace(/\bshall have dominion\b/g, 'will rule')
    .replace(/\bshall perish\b/g, 'will perish')
    .replace(/\bshall afflict\b/g, 'will afflict')
    .replace(/\bshall live\b/g, 'will live')
    .replace(/\bI shall\b/g, 'I will')
    .replace(/\bhe shall\b/g, 'he must')
    .replace(/\bshe shall\b/g, 'she must')
    .replace(/\bthey shall\b/g, 'they must')
    .replace(/\bYou shall\b/g, 'You must')
    .replace(/\byou shall\b/g, 'you must')
    .replace(/\bAaron shall\b/g, 'Aaron must')
    .replace(/\bMoses shall\b/g, 'Moses must')
    .replace(/\bthe priest shall\b/g, 'the priest must')
    .replace(/\bThe priest shall\b/g, 'The priest must')
    .replace(/\bshall\b/g, 'must')
}

function clarifySensitiveLanguage(text) {
  return text
    .replace(/\bno man has lain with you\b/g, 'no man has had sexual relations with you')
    .replace(/\bsome man has lain with you besides your husband\b/g, 'another man has had sexual relations with you besides your husband')
    .replace(/\bhas lain with you\b/g, 'has had sexual relations with you')
    .replace(/\bknown man by lying with him\b/g, 'had sexual relations with a man')
    .replace(/\bknown a man by lying with him\b/g, 'had sexual relations with a man')
    .replace(/\bwho has known man by lying with him\b/g, 'who has had sexual relations with a man')
    .replace(/\bwho have not known man by lying with him\b/g, 'who have not had sexual relations with a man')
    .replace(/\blie with her carnally\b/g, 'have sexual relations with her')
    .replace(/\blies with her carnally\b/g, 'has sexual relations with her')
    .replace(/\blie with\b/g, 'have sexual relations with')
    .replace(/\blies with\b/g, 'has sexual relations with')
}

function polishText(text) {
  return text
    .replace(/\bbehold, /gi, '')
    .replace(/\bmust must\b/g, 'must')
    .replace(/\bwill must\b/g, 'will')
    .replace(/\bmust be must\b/g, 'must be')
    .replace(/\bHe who\b/g, 'Whoever')
    .replace(/\bhe who\b/g, 'whoever')
    .replace(/\bhim who\b/g, 'the person who')
    .replace(/\bEveryone who\b/g, 'Everyone who')
    .replace(/\bEveryone of them\b/g, 'Every one of them')
    .replace(/\beveryone of them\b/g, 'every one of them')
    .replace(/\bWith you there must be\b/g, 'With you there will be')
    .replace(/\bAll the whole group\b/g, 'All the people')
    .replace(/\ball the people of the people of Israel\b/g, 'all the people of Israel')
    .replace(/\ball the whole group\b/g, 'all the people')
    .replace(/\ball the people of the people of Israel\b/g, 'all the people of Israel')
    .replace(/\bwhole group of the whole group\b/g, 'whole group')
    .replace(/\bwhole whole group\b/g, 'whole group')
    .replace(/\bpeople of Israel of the people of Israel\b/g, 'people of Israel')
    .replace(/\bpeople of Israel of Israel\b/g, 'people of Israel')
    .replace(/\bthose who were counted of them\b/g, 'those counted from them')
    .replace(/\bthose who were counted of it\b/g, 'those counted from them')
    .replace(/\bthose who were counted of the\b/g, 'those counted from the')
    .replace(/\bwere counted of you\b/g, 'were counted from you')
    .replace(/\bwere counted of them\b/g, 'were counted from them')
    .replace(/\bwere counted of the\b/g, 'were counted from the')
    .replace(/\bcounted of the\b/g, 'counted from the')
    .replace(/\bnumbered of them\b/g, 'counted from them')
    .replace(/\baccording to those who were counted of them\b/g, 'according to those counted from them')
    .replace(/\baccording to those who were counted of the\b/g, 'according to those counted from the')
    .replace(/\baccording to the command of the Lord by Moses\b/g, 'as the Lord commanded through Moses')
    .replace(/\bas the Lord commanded Moses\b/g, 'as the Lord commanded Moses')
    .replace(/\bwhich the Lord commanded Moses\b/g, 'which the Lord commanded Moses')
    .replace(/\bthe anger of the Lord was kindled\b/g, "the Lord's anger burned")
    .replace(/\bthe Lord's anger was kindled\b/g, "the Lord's anger burned")
    .replace(/\banger burned\b/g, 'anger burned')
    .replace(/\. the Lord\b/g, '. The Lord')
    .replace(/"the Lord\b/g, '"The Lord')
    .replace(/\bThe soul of the people\b/g, 'The people')
    .replace(/\bthe person must be cut off\b/g, 'the person must be removed')
    .replace(/\bvows a vow to the Lord\b/g, 'makes a serious promise to the Lord')
    .replace(/\bvows a vow\b/g, 'makes a serious promise')
    .replace(/\bvowed\b/g, 'made a serious promise')
    .replace(/\bvows\b/g, 'serious promises')
    .replace(/\bvow\b/g, 'serious promise')
    .replace(/\bpledges\b/g, 'binding promises')
    .replace(/\bpledge\b/g, 'binding promise')
    .replace(/\bto bind his person with a bond\b/g, 'to bind himself with a binding promise')
    .replace(/\bbinds herself by a binding promise\b/g, 'binds herself with a binding promise')
    .replace(/\bbinds herself by a bond\b/g, 'binds herself with a binding promise')
    .replace(/\bbound her person\b/g, 'bound herself')
    .replace(/\bbound his person\b/g, 'bound himself')
    .replace(/\bbound herself by a bond with an oath\b/g, 'bound herself with an oath')
    .replace(/\bbound her person by a bond with an oath\b/g, 'bound herself with an oath')
    .replace(/\bbind the person\b/g, 'make a binding promise')
    .replace(/\bbond of her person\b/g, 'binding promise she made')
    .replace(/\bthe rash utterance of her lips\b/g, 'the quick promise she spoke')
    .replace(/\brash utterance of her lips\b/g, 'quick promise she spoke')
    .replace(/\bproceeds out of his mouth\b/g, 'he has spoken')
    .replace(/\bwhatever proceeded out of her lips\b/g, 'whatever she spoke')
    .replace(/\bmade them null and void\b/g, 'canceled them')
    .replace(/\bmakes void\b/g, 'cancels')
    .replace(/\bmake it void\b/g, 'cancel it')
    .replace(/\bmake them void\b/g, 'cancel them')
    .replace(/\bmade them void\b/g, 'canceled them')
    .replace(/\bhas made them void\b/g, 'has canceled them')
    .replace(/\bheld his peace at her\b/g, 'said nothing to her')
    .replace(/\bdidn't disallow her\b/g, "didn't forbid her")
    .replace(/\bevery binding oath to afflict the person\b/g, 'every binding oath that requires her to go without something')
    .replace(/\bmust stand against her\b/g, 'must remain her responsibility')
    .replace(/\bher husband may establish it\b/g, 'her husband may let it stand')
    .replace(/\bhe establishes all her serious promises\b/g, 'he lets all her serious promises stand')
    .replace(/\bmust be cut off\b/g, 'must be removed')
    .replace(/\bwill cut him off\b/g, 'will remove him')
    .replace(/\bwill cut her off\b/g, 'will remove her')
    .replace(/\bwill cut them off\b/g, 'will remove them')
    .replace(/\bto the end that\b/g, 'so that')
    .replace(/\bin very deed\b/g, 'truly')
    .replace(/\btruly-as\b/g, 'truly, as')
    .replace(/\bGod, the God of the spirits of all flesh\b/g, 'God, the God of the spirits of all living beings')
    .replace(/\bthe Lord, the God of the spirits of all flesh\b/g, 'the Lord, the God of the spirits of all living beings')
    .replace(/\btherein\b/g, 'there')
    .replace(/\bso that they may dwell therein\b/g, 'so that they may live there')
    .replace(/\bdwell therein\b/g, 'live there')
    .replace(/\bdwell in\b/g, 'live in')
    .replace(/\bdwelling according to\b/g, 'camping according to')
    .replace(/\bdwellings\b/g, 'homes')
    .replace(/\bsojourns with you\b/g, 'lives with you')
    .replace(/\bforeigner lives as a foreigner with you\b/g, 'foreigner lives with you')
    .replace(/\bforeigner who lives as a foreigner with you\b/g, 'foreigner who lives with you')
    .replace(/\bwho lives as a foreigner with you\b/g, 'who lives with you')
    .replace(/\bforeigner who lives as a foreigner among them\b/g, 'foreigner who lives among them')
    .replace(/\bwho lives as a foreigner among them\b/g, 'who lives among them')
    .replace(/\bstranger who lives as a foreigner with you\b/g, 'foreigner who lives with you')
    .replace(/\bfrom twenty years old and upward\b/g, 'from twenty years old and older')
    .replace(/\bfrom a month old and upward\b/g, 'from a month old and older')
    .replace(/\bfrom thirty years old and upward\b/g, 'from thirty years old and older')
    .replace(/\bfrom fifty years old and upward\b/g, 'from fifty years old and older')
    .replace(/\bfrom five years old and upward\b/g, 'from five years old and older')
    .replace(/\bfar from off\b/g, 'far from')
    .replace(/\bout of the midst of\b/g, 'out from among')
    .replace(/\bfamilies, by their family houses\b/g, 'families and family houses')
    .replace(/\bby their families, by their family houses\b/g, 'by their families and family houses')
    .replace(/\beach one head of his family house\b/g, 'each one a leader of his family house')
    .replace(/\bwhich are mentioned by name\b/g, 'who were named')
    .replace(/\bwho are mentioned by name\b/g, 'who were named')
    .replace(/\bThese are those who were called of the whole group\b/g, 'These were the ones called from the whole group')
    .replace(/\bthese are they who were over\b/g, 'these were the ones over')
    .replace(/\bafter the tribe of their fathers\b/g, 'by their ancestral tribe')
    .replace(/\bThe descendants of Joseph\b/g, 'The descendants of Joseph')
    .replace(/\bOf the descendants of Joseph: of the descendants of Ephraim\b/g, 'Of the descendants of Joseph: of Ephraim')
    .replace(/\btribe of the descendants of ([A-Z][a-z]+)\b/g, 'tribe of $1')
    .replace(/\bprince of the descendants of ([A-Z][a-z]+)\b/g, 'leader of the descendants of $1')
    .replace(/\bbanner of the camp of the descendants of ([A-Z][a-z]+)\b/g, 'banner of the camp of $1')
    .replace(/\bthe descendants of ([A-Z][a-z]+), their generations\b/g, 'the descendants of $1, by their generations')
    .replace(/\bcalled according to\b/g, 'called by')
    .replace(/\bThis must be to you for a rule\b/g, 'This will be a rule for you')
    .replace(/\bthey must be to you for a memorial\b/g, 'they will be a memorial for you')
    .replace(/\bWhen either man or woman must make\b/g, 'When either a man or a woman makes')
    .replace(/\bhe makes unclean the head of his separation\b/g, 'his special separation becomes unclean')
    .replace(/\bthe head of his separation\b/g, 'the hair of his separation')
    .replace(/\bsinned by reason of the dead\b/g, 'sinned because of the dead body')
    .replace(/\bthe former days must be void\b/g, 'the former days will not count')
    .replace(/\bIt must be, if you go with us-yes, it must be-that\b/g, 'If you go with us,')
    .replace(/\bIt must be that the man whom the Lord chooses, he will be holy\b/g, 'The man whom the Lord chooses will be holy')
    .replace(/\bthe man whom the Lord chooses, he will be holy\b/g, 'the man whom the Lord chooses will be holy')
    .replace(/\bwhom he must choose\b/g, 'whom he chooses')
    .replace(/\bmust one man sin\b/g, 'if one man sins')
    .replace(/\bthen you must understand\b/g, 'then you will understand')
    .replace(/\bHereby you must know\b/g, 'By this you will know')
    .replace(/\bwhich they complain against you\b/g, 'which they bring against you')
    .replace(/\bHow long must I bear\b/g, 'How long will I bear')
    .replace(/\bthe whole group that complain\b/g, 'the whole group that complains')
    .replace(/\bevil whole group that complain\b/g, 'evil whole group that complains')
    .replace(/\bwho complain against\b/g, 'who complain against')
    .replace(/\bpestilence\b/g, 'terrible sickness')
    .replace(/\bhave tempted me\b/g, 'have tested me')
    .replace(/\bhe has slain them\b/g, 'he has killed them')
    .replace(/\bthose who despised me see it\b/g, 'those who despised me will see it')
    .replace(/\bthey must not see the land\b/g, 'they will not see the land')
    .replace(/\bneither must any of those\b/g, 'nor will any of those')
    .replace(/\bnor will any of those who despised me will see it\b/g, 'nor will any of those who despised me see it')
    .replace(/\ball the earth must be filled\b/g, 'all the earth will be filled')
    .replace(/\bHis offspring must possess it\b/g, 'His children will possess it')
    .replace(/\bhim I will bring into\b/g, 'I will bring him into')
    .replace(/\byour dead bodies must fall\b/g, 'your dead bodies will fall')
    .replace(/\bYour dead bodies must fall\b/g, 'Your dead bodies will fall')
    .replace(/\bsurely you must not come into the land\b/g, 'surely you will not come into the land')
    .replace(/\bI will bring your little ones that you said should be captured or killed in\b/g, 'I will bring your little ones, whom you said would be captured, into it')
    .replace(/\bthey must know the land\b/g, 'they will know the land')
    .replace(/\bYour children must be wanderers\b/g, 'Your children will be wanderers')
    .replace(/\bmust bear your unfaithfulness\b/g, 'will bear your unfaithfulness')
    .replace(/\bthey must be consumed\b/g, 'they will be consumed')
    .replace(/\bthere they must die\b/g, 'there they will die')
    .replace(/\byou will know my alienation\b/g, 'you will know my displeasure')
    .replace(/\bit must not prosper\b/g, 'it will not succeed')
    .replace(/\bwill make of you a nation\b/g, 'will make you into a nation')
    .replace(/\bAll the people before all the people of the whole group of the people of Israel\b/g, 'all the people of Israel')
    .replace(/\bbefore all the people of the whole group of the people of Israel\b/g, 'before all the people of Israel')
    .replace(/\?\s+and how long\b/g, '? And how long')
    .replace(/\bmade all the people to complain\b/g, 'made all the people complain')
    .replace(/\bmade all the community to complain\b/g, 'made all the community complain')
    .replace(/\bthe people who we saw\b/g, 'the people we saw')
    .replace(/"we are\b/g, '"We are')
    .replace(/\. we are\b/g, '. We are')
    .replace(/\bdidn't depart out of the camp\b/g, "didn't leave the camp")
    .replace(/\beven to Hormah\b/g, 'as far as Hormah')
    .replace(/\bOne law and one command must be for you\b/g, 'One law and one command will be for you')
    .replace(/\bafter which you used to play the person living in sexual sin\b/g, 'by which you used to be unfaithful')
    .replace(/\bto play the person living in sexual sin after them\b/g, 'to be unfaithful by following them')
    .replace(/\bcommitted a trespass against her husband\b/g, 'acted unfaithfully against her husband')
    .replace(/\btrespass against the Lord\b/g, 'act unfaithfully against the Lord')
    .replace(/\bcommits a trespass against the Lord\b/g, 'acts unfaithfully against the Lord')
    .replace(/\bany sin that men commit\b/g, 'any sin that people commit')
    .replace(/\bin respect of whom he has been guilty\b/g, 'against whom he has done wrong')
    .replace(/\bheave offering\b/g, 'special offering')
    .replace(/\bbeing under your husband's authority\b/g, 'while you are married to your husband')
    .replace(/\bbeing under her husband\b/g, 'while she is married to her husband')
    .replace(/\bMay the Lord make you a curse and an oath\b/g, 'May the Lord make your case a warning and an oath')
    .replace(/\ballows your thigh waste away\b/g, 'allows your thigh to waste away')
    .replace(/\bthigh to fall away\b/g, 'thigh waste away')
    .replace(/\byour thigh fall away\b/g, 'your thigh waste away')
    .replace(/\ballows your thigh waste away\b/g, 'allows your thigh to waste away')
    .replace(/\bmake your body swell, and your thigh waste away\b/g, 'make your body swell and make your thigh waste away')
    .replace(/\bher thigh will fall away\b/g, 'her thigh will waste away')
    .replace(/\bwater of bitterness\b/g, 'bitter water')
    .replace(/\bwater that causes the curse\b/g, 'water connected with the curse')
    .replace(/\bWhen he has made her drink the water, then it must happen\b/g, 'When he has made her drink the water')
    .replace(/\bthen it must happen, if\b/g, 'then if')
    .replace(/\bif she is made unclean and has acted unfaithfully against her husband, that the water connected with the curse will enter into her and become bitter\b/g, 'if she is made unclean and has acted unfaithfully against her husband, the water connected with the curse will enter into her and become bitter')
    .replace(/\bshe must be free\b/g, 'she will be free')
    .replace(/\bmust conceive offspring\b/g, 'will conceive children')
    .replace(/\bmust execute on her all this law\b/g, 'must carry out this whole law for her')
    .replace(/\bmake their camp unclean\b/g, 'make their camp unclean')
    .replace(/\bmake unclean their camp\b/g, 'make their camp unclean')
    .replace(/\bmakes unclean the Lord's tent\b/g, "makes the Lord's tent unclean")
    .replace(/\bmake unclean the Lord's tent\b/g, "make the Lord's tent unclean")
    .replace(/\bone who is slain with a sword\b/g, 'someone killed with a sword')
    .replace(/\bthat was slain\b/g, 'who was killed')
    .replace(/\bwho was slain\b/g, 'who was killed')
    .replace(/\bwho was killed, who was killed\b/g, 'who was killed')
    .replace(/\bThis is the thing which the Lord has commanded\b/g, 'This is what the Lord has commanded')
    .replace(/\bThis is the thing which the Lord commands concerning\b/g, 'This is what the Lord commands about')
    .replace(/\bmade a serious promise a serious promise\b/g, 'made a serious promise')
    .replace(/\bmakes a special serious promise, the serious promise of a Nazirite\b/g, 'makes a special Nazirite promise')
    .replace(/\bthe Nazirite who serious promises\b/g, 'the Nazirite who makes a serious promise')
    .replace(/\bwhich he serious promises\b/g, 'which he makes')
    .replace(/\bforbids her in the day that he hears\b/g, 'forbids her on the day he hears')
    .replace(/\bbeing in her family house, in her youth\b/g, "while she is young and living in her father's house")
    .replace(/\bbeing in her youth, in her family house\b/g, "while she is young and living in her father's house")
    .replace(/\bwhile her serious promises are on her\b/g, 'while she is under her serious promises')
    .replace(/\bin the day that he hears it\b/g, 'on the day he hears it')
    .replace(/\bin the day that he heard it\b/g, 'on the day he heard it')
    .replace(/\bin the day that he heard them\b/g, 'on the day he heard them')
    .replace(/\bmust not stand\b/g, 'must not count')
    .replace(/\bmust stand\b/g, 'must still count')
    .replace(/\bHe has established them\b/g, 'He has let them stand')
    .replace(/\bmakes them null and void\b/g, 'cancels them')
    .replace(/\btake the hair of the hair of his separation\b/g, 'take the hair he shaved from his separated head')
    .replace(/\bBut the man who will be unclean, and must not purify himself\b/g, 'But the man who is unclean and does not purify himself')
    .replace(/\bthe person who touched the dead body must purify himself\b/g, 'the person who touched the dead body must purify himself')
    .replace(/\bwithout meaning to, and didn't know it\b/g, 'without meaning to and did not know it')
    .replace(/\bbegan to play the person living in sexual sin with\b/g, 'began to sin sexually with')
    .replace(/^one of the people of Israel\b/, 'One of the people of Israel')
    .replace(/\bIt must be to him, and to his offspring after him, the covenant of an everlasting priesthood\b/g, 'It will be for him, and for his children after him, the covenant of an everlasting priesthood')
    .replace(/\bIt must be to the people of Israel, and to the foreigner who lives among them, for a rule forever\b/g, 'It will be a rule forever for the people of Israel and for the foreigner who lives among them')
    .replace(/\bIt must be a perpetual rule to them\b/g, 'It will be a lasting rule for them')
    .replace(/\bIt must be to you for a fringe\b/g, 'This will be a fringe for you')
    .replace(/\bIt must be a rule forever\b/g, 'It will be a lasting rule')
    .replace(/\bgathered people is to be gathered together\b/g, 'gathered people are to gather')
    .replace(/\btwo day by day\b/g, 'two each day')
    .replace(/\bwhich was ordained in Mount Sinai\b/g, 'which was appointed at Mount Sinai')
    .replace(/\bOn the fifteenth day of this month must be a feast\b/g, 'On the fifteenth day of this month there must be a feast')
    .replace(/\bIn the first day must be a holy gathering\b/g, 'On the first day there must be a holy gathering')
    .replace(/\btwo tenth parts\b/g, 'two tenths')
    .replace(/\bone tenth part\b/g, 'one tenth')
    .replace(/\bthe third part\b/g, 'one third')
    .replace(/\bthe fourth part\b/g, 'one fourth')
    .replace(/\boffer an offering burned on the altar\b/g, 'bring an offering burned on the altar')
    .replace(/\bin offering an offering burned on the altar\b/g, 'when bringing an offering burned on the altar')
    .replace(/\boffering an offering burned on the altar\b/g, 'bringing an offering burned on the altar')
    .replace(/\bthat person must be utterly cut off\b/g, 'that person must be completely removed')
    .replace(/\bmust be utterly cut off\b/g, 'must be completely removed')
    .replace(/\bDon't cut off the tribe of the families of the Kohathites from among the Levites\b/g, "Don't let the tribe of the families of the Kohathites be destroyed from among the Levites")
    .replace(/\bEverything that opens the womb, of all flesh which they offer to the Lord, both people and animals, must be yours\b/g, 'Every firstborn that opens the womb, which they offer to the Lord, whether human or animal, must be yours')
    .replace(/\bThey brought the captives with the plunder and the plunder\b/g, 'They brought the captives and the plunder')
    .replace(/\bwith the rest of their slain\b/g, 'with the rest of those who were killed')
    .replace(/^these caused\b/, 'These caused')
    .replace(/\bto commit act unfaithfully against\b/g, 'to act unfaithfully against')
    .replace(/\bCount the plunder that was taken, both people and animals\b/g, 'Count the plunder that was taken, both people and animals')
    .replace(/\bone drawn out of every fifty\b/g, 'one out of every fifty')
    .replace(/\bthere lacks not one man of us\b/g, 'not one man of us is missing')
    .replace(/\ball worked jewels\b/g, 'all the worked jewelry')
    .replace(/\bmust be wife to one of the family of the tribe of her father\b/g, "must marry someone from the family of her father's tribe")
    .replace(/\bThese are the commands and the commands which the Lord commanded by Moses\b/g, 'These are the commands and rules that the Lord commanded through Moses')
    .replace(/\bwhich the Lord commanded by Moses\b/g, 'which the Lord commanded through Moses')
    .replace(/\bto which they must belong\b/g, 'to which they will belong')
    .replace(/\bSo must no inheritance of the people of Israel move\b/g, 'So no inheritance of the people of Israel may move')
    .replace(/\bSo must no inheritance move\b/g, 'So no inheritance may move')
    .replace(/\bThe tribe of the sons of Joseph speak what is right\b/g, 'The tribe of the sons of Joseph speaks what is right')
    .replace(/\bthis is the land that must fall to you for an inheritance\b/g, 'this is the land that will be assigned to you as an inheritance')
    .replace(/\bhas made unclean the sanctuary of the Lord\b/g, "has made the Lord's sanctuary unclean")
    .replace(/\bperson that touches it\b/g, 'person who touches it')
    .replace(/\btwo male lambs a year old with nothing wrong with it\b/g, 'two male lambs a year old with nothing wrong with them')
    .replace(/\bmale lambs a year old with nothing wrong with it\b/g, 'male lambs a year old with nothing wrong with them')
    .replace(/\bseven male lambs a year old with nothing wrong with it\b/g, 'seven male lambs a year old with nothing wrong with them')
    .replace(/\bfourteen male lambs a year old, all with nothing wrong with it\b/g, 'fourteen male lambs a year old, all with nothing wrong with them')
    .replace(/\bThey must be with nothing wrong with it\b/g, 'They must have nothing wrong with them')
    .replace(/\bSee that they are with nothing wrong with it\b/g, 'See that they have nothing wrong with them')
    .replace(/\ball with nothing wrong with it\b/g, 'all with nothing wrong with them')
    .replace(/\bCaleb stilled the people\b/g, 'Caleb quieted the people')
    .replace(/\bwherein\b/g, 'in which')
    .replace(/\bwiles\b/g, 'tricks')
    .replace(/\bwith their tricks, in which they have deceived you\b/g, 'with their tricks, by which they deceived you')
    .replace(/\binto the pavilion\b/g, 'into the tent')
    .replace(/\bthrust herself to the wall\b/g, 'pressed herself against the wall')
    .replace(/\bthrust both of them through\b/g, 'pierced both of them')
    .replace(/\bmust return into the city of his refuge\b/g, 'must return to his city of refuge')
    .replace(/\bthe person who killed someone must dwell\b/g, 'the person who killed someone must live')
    .replace(/\bmust not die until he stands before the whole group for judgment\b/g, 'must not die before he stands before the whole group for judgment')
    .replace(/\bWater must flow from his buckets\b/g, 'Water will flow from his buckets')
    .replace(/\bHis seed must be in many waters\b/g, 'His seed will be in many waters')
    .replace(/\bHis king must be higher than Agag\b/g, 'His king will be higher than Agag')
    .replace(/\bHis kingdom must be exalted\b/g, 'His kingdom will be lifted high')
    .replace(/\bHe must consume\b/g, 'He will consume')
    .replace(/\bmust break their bones\b/g, 'will break their bones')
    .replace(/\bwho must rouse him up\b/g, 'who will rouse him up')
    .replace(/\bwhat this people must do to your people\b/g, 'what this people will do to your people')
    .replace(/\bEdom must be a possession\b/g, 'Edom will be a possession')
    .replace(/\balso must be a possession\b/g, 'also will be a possession')
    .replace(/\bOut of Jacob must one have dominion\b/g, 'Out of Jacob one will rule')
    .replace(/\bKain must be wasted\b/g, 'Kain will be wasted')
    .replace(/\bnations, But\b/g, 'nations, but')
    .replace(/\bAlmighty, Falling down\b/g, 'Almighty, falling down')
    .replace(/\bparable\b/g, 'message')
    .replace(/\bthe man whose eyes are open says\b/g, 'the man whose eyes are opened says')
    .replace(/\bthe the\b/g, 'the')
    .replace(/\bof of\b/g, 'of')
    .replace(/\ba an\b/g, 'an')
    .replace(/\ban detestable thing\b/g, 'a detestable thing')
    .replace(/\ban terrible sickness\b/g, 'a terrible sickness')
    .replace(/\ba offering\b/g, 'an offering')
    .replace(/\s+([,.;:!?])/g, '$1')
    .replace(/\(\s+/g, '(')
    .replace(/\s+\)/g, ')')
    .replace(/\s+/g, ' ')
    .trim()
    .replace(/^the Lord\b/, 'The Lord')
}

main().catch(error => {
  console.error(error)
  process.exit(1)
})
